/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_administrator_jnihello_HelloJni */

#ifndef _Included_com_example_administrator_jnihello_HelloJni
#define _Included_com_example_administrator_jnihello_HelloJni
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_administrator_jnihello_HelloJni
 * Method:    sayhello
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_com_example_administrator_jnihello_HelloJni_sayhello
  (JNIEnv *, jclass, jint);

/*
 * Class:     com_example_administrator_jnihello_HelloJni
 * Method:    returnString
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_administrator_jnihello_HelloJni_returnString
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
